### ISSUE TITLE
Issue with scripts

### ISSUE THREAD

**Issue by Ergus** [vale981/py-vterm-interaction.el#2]
Hi:

I have installed the package from melpa and I use this config:

```
(use-package py-vterm-interaction
  :defer t
  :init
  (add-hook 'python-ts-mode-hook #'py-vterm-interaction-mode)
  (setq-default py-vterm-interaction-repl-program "ipython3 -i"
		py-vterm-interaction-silent-cells t))
```

However it shows an error because the `scripts/is_ipython.py` does not exist. I checked the installation folder and indeed the `scripts` directory was not installed.

**Comment by vale981** [comment]
i must have messed up the melpa recipe, sorry for that!

**Comment by vale981** [comment]
See: https://github.com/melpa/melpa/pull/9171
